### Create new user
POST {{api}}/users/signup
Content-Type: application/json

{
  "name": "Delano",
  "email": "cedric_cappsi@reynolds.mb",
  "password": "rZiCFh9oABw1xNJi",
  "passwordChangedAt": "2024-08-10T14:57:00.000Z"
}

> {%
  client.global.set("auth_token", response.body.token);
%}

### Get user
GET {{api}}/users

### Login
POST {{api}}/users/login
Content-Type: application/json

{
  "email": "norvell_sturtevantfpp@carrying.sys",
  "password": "rZiCFh9oABw1xNJi"
}

> {%
  client.global.set("auth_token", response.body.token);
%}

### Get all tours
GET {{api}}/tours
Authorization: Bearer {{auth_token}}

### Delete tour
DELETE {{api}}/tours/9
Authorization: Bearer {{auth_token}}