### Create new user
POST {{api}}/users/signup
Content-Type: application/json

{
  "name": "Delano",
  "email": "cedric_cappsi@reynolds.mb",
  "password": "rZiCFh9oABw1xNJi",
  "passwordChangedAt": "2024-08-10T14:57:00.000Z"
}

### Get user
GET {{api}}/users

### Login
POST {{api}}/users/login
Content-Type: application/json

{
  "email": "cedric_cappsi@reynolds.mb",
  "password": "rZiCFh9oABw1xNJi"
}